---
# tasks file for temp_message

- name: Check that mosquitto-clients is installed
  become: true
  apt:
    pkg:
      - mosquitto-clients
      - cron
    update_cache: yes

- name: Copy the temperature measurement script to the host
  become: true
  template:
    src: temp-monitor.sh.j2
    dest: /root/temp-monitor.sh
    owner: root
    group: root
    mode: o+x

- name: Setup cronjob in cron.d directory under telemetry
  cron:
    name: Temperature Monitor
    user: root
    job: "/root/temp-monitor.sh > /var/log/tempmonitor.log 2>&1"
    cron_file: telemetry

- name: Enable cron service
  systemd:
    name: cron.service
    enabled: yes
  register: cron_enabled

- name: Start cron service
  systemd:
    name: cron.service
    state: started
  when: cron_enabled.changed