---
# tasks file for temp_message

- name: Check that mosquitto-clients is installed
  become: true
  ansible.builtin.apt:
    pkg:
      - mosquitto-clients
      - cron
      - mawk
    update_cache: yes

- name: Copy the telemetry script to the host
  become: true
  ansible.builtin.template:
    src: "{{ item }}.sh.j2"
    dest: "/root/{{ item }}.sh"
    owner: root
    group: root
    mode: o+x
  loop:
    - temp-monitor
    - diskspace-monitor

- name: Setup cronjob in cron.d directory under telemetry
  become: true
  ansible.builtin.cron:
    name: "{{ item.name }}"
    user: root
    job: "/root/{{ item.job }}.sh > /var/log/{{ item.log }}.log 2>&1"
    cron_file: telemetry
  loop:
    - job: temp-monitor
      name: Temperature Monitor
      log: tempmonitor
    - job: diskspace-monitor
      name: Diskspace Monitor
      log: diskspace-monitor

- name: Enable cron service
  become: true
  ansible.builtin.systemd:
    name: cron.service
    enabled: yes
  notify: Start crond
